export enum CONSTANT_TEXT {
  LOGIN = 'Login',
  DASHBOARD = 'Dashboard',
  NO_DATA_FOUNG = 'There is no data',
  NO_DATA_FOUNG2 = 'Refresh after some time',
  LOADING = 'Loading...',
  LARGE = 'large',
  ARE_YOUSURE_GO_BACK = 'Are you sure you want to go back?',
  CANCEL = 'Cancel',
  SIGN_IN = 'Log In',
  EMAIL_ADDRESS = 'Email address',
  PHONE_NO = 'Phone Number',
  PASSWORD = 'Password',
  DONT_HAVE_ACCOUNT = 'No account? Create one here! ',
  SIGN_UP_HERE = 'Sign Up!',
  BACK = 'Back',
  VERIFY_OTP = 'Verify OTP',
  PLEASE_ENTER_CODE = 'Please Enter code received on',
  VERIFY = 'Verify Now',
  RESEND_OTP = 'Resend OTP',
  GO_BACK = 'Go Back',
  PROFILE = 'Profile',
  NAME = 'Name',
  EMAIL = 'Email Address',
  PHONE = 'Phone Number',
  SAVE = 'Save',
  SUCCESS = 'success',
  PROFILE_SAVE = 'Profile Saved',
  SETTINGS = 'Settings',
  LOGOUT = 'Log out',
  MY_PROFILE = 'My Profile',
  REGISTER = 'Register',
  EMAIL_USERNAME = 'Email/Username',
  I_ACCEPT_THE = 'I accept the',
  TERMS_AND_CONDITION = 'Terms & Conditions',
  SIGN_UP = 'Sign up',
  ALREADY_HAVE_ACCOUNT = 'Already have an account?',
  SIGN_IN_HERE = ' Log in!',
  AUTO_REFRESH = 'Refresh',
  DAYS_AGO = ' days ago',
  DAY_AGO = ' day ago',
  BLANK_FIELD = '---',
  DELETE = 'Delete',
  ADD_TO_WATCHLIST = 'ADD TO WATCHLIST',
  SAVE_TO_WATCHLIST = 'Save to Watchlist',
  CHOOSE_A_WATCHLIST = 'Choose a watchlist',
  CREATE_NEW = 'Create New',
  REMOVE_FROM_WATCHLIST = 'Remove from Watchlist',
  REMOVE = 'Remove',
  ALERTS = 'Alerts',
  NO_ALERT = 'No Alerts...',
  GET_CODE = 'Get Code',
  VERIFY_YOUR_OTP = 'OTP Verification',
  ENTER_OTP = 'Enter OTP',
  DEACTIVATE_DES = 'Please be aware that deactivating your StockYaari account involves the loss of access to the app, necessitating a activation your account. Make sure you have considered these consequences before proceeding with the deactivation process.',
  HOW_IT_WORK = 'How it work',
  HELP_DESC = "Welcome to StockYaari! We're here to guide you through the features and functionality of our application. If you have any questions or need assistance, you've come to the right place.",
  NO = 'No',
  YES = 'Yes',
  ACTIVATE = 'Activate',
  YOU_HAVE_NO_LONGER = 'You will no longer have access\n to the StockYaari app.',
  BACK_TESING_DEC = 'You can do back testing of this stock by selecting date (only available for last 2 years). It will show you the previous recommendation of this app on that particular date. It will help you to build trust on our recommendations.',
  DEACTIVATE_TITLE = 'Your account has been deactivated. We appreciate your time with us and hope to welcome you back soon. To access your account again, simply log in using your user ID and password. If you have any questions or need assistance, feel free to contact our support team.',
  DELETE_TITLE = 'Your account has been deleted. We appreciate your time with us and hope to welcome you back soon. If you have any questions or need assistance, feel free to contact our support team.',
  NO_INTERNET_TITLE = "It looks like you're offline",
  NO_INTERNET_DESC = 'Check if your device is connected to a\nmobile network or wifi',
  SEE_ALL = 'See all',
  YES_DELETE = 'Yes, Delete',
  YES_CLOSE = 'Yes, Close',
  YES_REMOVE = 'Yes, Remove',
  NOT_NOW = 'Not Now',
  TRIGGERED_ALERTS = 'TRIGGERED ALERTS',
  SET_GREEN_SIGNAL = 'Set Green Signals On Star Rated Stocks By Default. So Whenever Any Star Rated Stock Trigger With Green Signal You Will Get The Notification.',
  TOTAL_ALERTS = 'Total Active Alerts',
  TOTAL_TRIGGER_ALERTS = 'Total Triggered Alerts',
  SEARCH_ANY_STOCKS = `Search any stock`,
  CONTACT_SUPPORT_EMAIL = 'support@stockyaari.com',
  SEARCH_WATCHLIST_STOCKS = `Search Watchlist stocks...`,
  YOUR_PLAN_DETAIL = 'Your Plan Details',
  ABOUT_US = 'About Us',
}
export const ERROR_MESSAGES = {
  NO_INTERNET: 'No internet',
  DELETE_SELECTED_ITEM: 'Select the item first',
  TOKEN_EXPIRE: 'Token expired, try login again',
  ACCOUNT_DELETED: 'Account deleted successfully.',
  TO_ACCESS_THIS_FETURE: 'To access this exclusive feature, please subscribe to our premium plan.',
};
export const HEADER_TITLE = {
  STAR_STOCK: 'Star Stocks Triggered ',
  YOUR_STOCK_ALERT: 'Stock Triggered ',
  CUSTOMER_CARE: 'Customer Care',
  TRADING_CALLS:'Trading Calls'
};
