const FONTS = {
  OpenSansBold: 'OpenSans-Bold',
  OpenSansBoldItalic: 'OpenSans-BoldItalic',
  OpenSansExtraBold: 'OpenSans-ExtraBold',
  OpenSansExtraBoldItalic: 'OpenSans-ExtraBoldItalic',
  OpenSansItalic: 'OpenSans-Italic',
  OpenSansLight: 'OpenSans-Light',
  OpenSansLightItalic: 'OpenSans-LightItalic',
  OpenSansMedium: 'OpenSans-Medium',
  OpenSansMediumItalic: 'OpenSans-MediumItalic',
  OpenSansRegular: 'OpenSans-Regular',
  OpenSansSemiBold: 'OpenSans-SemiBold',
  OpenSansSemiBoldItalic: 'OpenSans-SemiBoldItalic',
  
  RobotoBlack: 'Roboto-Black',
  RobotoBlackItalic: 'Roboto-BlackItalic',
  RobotoBold: 'Roboto-Bold',
  RobotoBoldItalic: 'Roboto-BoldItalic',
  RobotoItalic: 'Roboto-Italic',
  RobotoLight: 'Roboto-Light',
  RobotoLightItalic: 'Roboto-LightItalic',
  RobotoMedium: 'Roboto-Medium',
  RobotoMediumItalic: 'Roboto-MediumItalic',
  RobotoRegular: 'Roboto-Regular',
  RobotoThin: 'Roboto-Thin',
  RobotoThinItalic: 'Roboto-ThinItalic',
};
export default FONTS;
// export enum FONTS {
//   OpenSansBold = 'OpenSans-Bold',
//   OpenSansBoldItalic = 'OpenSans-BoldItalic',
//   OpenSansExtraBold = 'OpenSans-ExtraBold',
//   OpenSansExtraBoldItalic = 'OpenSans-ExtraBoldItalic',
//   OpenSansItalic = 'OpenSans-Italic',
//   OpenSansLight = 'OpenSans-Light',
//   OpenSansLightItalic = 'OpenSans-LightItalic',
//   OpenSansMedium = 'OpenSans-Medium',
//   OpenSansMediumItalic = 'OpenSans-MediumItalic',
//   OpenSansRegular = 'OpenSans-Regular',
//   OpenSansSemiBold = 'OpenSans-SemiBold',
//   OpenSansSemiBoldItalic = 'OpenSans-SemiBoldItalic',

//   RobotoBlack = 'Roboto-Black',
//   RobotoBlackItalic = 'Roboto-BlackItalic',
//   RobotoBold = 'Roboto-Bold',
//   RobotoBoldItalic = 'Roboto-BoldItalic',
//   RobotoItalic = 'Roboto-Italic',
//   RobotoLight = 'Roboto-Light',
//   RobotoLightItalic = 'Roboto-LightItalic',
//   RobotoMedium = 'Roboto-Medium',
//   RobotoMediumItalic = 'Roboto-MediumItalic',
//   RobotoRegular = 'Roboto-Regular',
//   RobotoThin = 'Roboto-Thin',
//   RobotoThinItalic = 'Roboto-ThinItalic',
// }

