export enum PixelSizes {
    ZERO = '0px',
    EIGHT = '8px',
    TWENTY = '20px',
    THIRTY = '30px',
    SEVENTY_ONE = '71px',
    ONE = '1px',
    TWO = '2px',
    THREE = '3px',
    FOUR = '4px',
    FIVE = '5px',
    SIX = '6px',
    SEVEN = '7px',
    FIFTEEN = '15px',
    TEN = '10px',
    SIXTEEN = '16px',
    THIRTY_FIVE = '35px',
    THIRTY_TWO = '32px',
    TWENTY_FOUR = '24px',
    FIFTY = '50px',
    SIXTY = '60px',
    VALUE_375 = '375px',
    EIGHTEEN = '18px',
    FORTY = '40px',
    VALUE_200 = '200px',
    VALUE_MIN_3 = '-3px',
  }
  