export const Recommended = [
  {index: '1', label: 'Green Signal ', value: 'Buy'},
  {index: '2', label: 'Red Alert', value: 'Sell'},
];
export const prevDay = [
  {index: '1', label: 'Today', value: 'latest'},
  {index: '2', label: '1-day ago', value: '1-day-ago'},
  {index: '3', label: '2-day ago', value: '2-day-ago'},
  {index: '4', label: '3-day ago', value: '3-day-ago'},
  {index: '5', label: '4-day ago', value: '4-day-ago'},
  {index: '6', label: '5-day ago', value: '5-day-ago'},
  {index: '7', label: '6-day ago', value: '6-day-ago'},
  {index: '8', label: '7-day ago', value: '7-day-ago'},
  // {index: '9', label: 'Older', value: 'older'},
];
export const Segment = [
  {index: '1', label: 'Cash', value: 'cash'},
  {index: '2', label: 'F&O', value: 'fo'},
  {index: '3', label: 'Futures', value: 'futures'},
  {index: '4', label: 'Mcx', value: 'mcx'},
  {index: '5', label: 'Nifty50', value: 'nifty50'},
  {index: '6', label: 'Nifty100', value: 'nifty100'},
  {index: '7', label: 'Nifty200', value: 'nifty200'},
  {index: '8', label: 'Nifty500', value: 'nifty500'},
];
export const Sector = [
  {index: '0', label: 'All', value: 'all'},
  {index: '1', label: 'Agro', value: 'agro'},
  {index: '2', label: 'Agrochemicals', value: 'agrochemicals'},
  {index: '3', label: 'Apparel', value: 'apparel'},
  {index: '4', label: 'Auto', value: 'auto'},
  {index: '5', label: 'Bank', value: 'bank'},
  {index: '6', label: 'Batteries', value: 'batteries'},
  {index: '7', label: 'Beverages', value: 'beverages'},
  {index: '8', label: 'Breweries', value: 'breweries'},
  {index: '9', label: 'Cement', value: 'cement'},
  {index: '10', label: 'Chemicals', value: 'chemicals'},
  {index: '11', label: 'Commodities', value: 'commodities'},
  {index: '12', label: 'Construction', value: 'construction'},
  {index: '13', label: 'Diversified', value: 'diversified'},
  {index: '14', label: 'Education', value: 'education'},
  {index: '15', label: 'Electricals', value: 'electricals'},
  {index: '16', label: 'Electronics', value: 'electronics'},
  {index: '17', label: 'Ethanol', value: 'ethanol'},
  {index: '18', label: 'Finance', value: 'finance'},
  {index: '19', label: 'FMCG', value: 'fmcg'},
  {index: '20', label: 'Glass', value: 'glass'},
  {index: '21', label: 'Healthcare', value: 'healthcare'},
  {index: '22', label: 'Hotels', value: 'hotels'},
  {index: '23', label: 'Industrials', value: 'industrials'},
  {index: '24', label: 'IT', value: 'IT'},
  {index: '25', label: 'Jewellery', value: 'jewellery'},
  {index: '26', label: 'Logistics', value: 'logistics'},
  {index: '27', label: 'Machinery', value: 'machinery'},
  {index: '28', label: 'Maharatna', value: 'maharatna'},
  {index: '29', label: 'Media', value: 'media'},
  {index: '30', label: 'Metal', value: 'metal'},
  {index: '31', label: 'Miniratna', value: 'miniratna'},
  {index: '32', label: 'Miscellaneous', value: 'miscellaneous'},
  {index: '33', label: 'Navratna', value: 'navratna'},
  {index: '34', label: 'Oil & Gas', value: 'oil&gas'},
  {index: '35', label: 'Packaging', value: 'packaging'},
  {index: '36', label: 'Paints', value: 'paints'},
  {index: '37', label: 'Petrochemicals', value: 'petrochemicals'},
  {index: '38', label: 'Pharmaceuticals', value: 'pharmaceuticals'},
  {index: '39', label: 'Power', value: 'power'},
  {index: '40', label: 'PSU', value: 'psu'},
  {index: '41', label: 'Publishing', value: 'publishing'},
  {index: '42', label: 'Ratings', value: 'ratings'},
  {index: '43', label: 'Real Estate', value: 'real&estate'},
  {index: '44', label: 'Renewable', value: 'renewable'},
  {index: '45', label: 'Retail', value: 'retail'},
  {index: '46', label: 'Rubber', value: 'rubber'},
  {index: '47', label: 'Shipbuilding', value: 'shipbuilding'},
  {index: '48', label: 'Sugar', value: 'sugar'},
  {index: '49', label: 'Telecom', value: 'telecom'},
  {index: '50', label: 'Textiles', value: 'textiles'},
  {index: '51', label: 'Trading', value: 'trading'},
  {index: '52', label: 'Tyres', value: 'tyres'},
  {index: '53', label: 'Utilities', value: 'utilities'},
];
